

#调试参数
node.enable_lucene_segment_infos_trace: true

#http.enabled: false

#集群名称
cluster.name: elasticsearch-2.4
#节点名称
node.name: zhengxgs-7.238

#当索引不存在的index的时候是否自动创建，默认true
action.auto_create_index: true
#是否是动态索引，默认true
index.mapper.dynamic: true
#是否自动生成ID
action.bulk.action.allow_id_generation: true

#合并的线程数，使用的是机械磁盘而非SSD的话设置为1最好
#机械磁盘在并发 I/O 支持方面比较差，所以我们需要降低每个索引并发访问磁盘的线程数。这个设置允许 max_thread_count + 2 个线程同时进行磁盘操作，也就是设置为 1 允许三个线程
#对于 SSD，可以忽略这个设置，默认是 Math.min(4, Runtime.getRuntime().availableProcessors() / 2) ，对 SSD 来说运行的很好。
index.merge.scheduler.max_thread_count: 1

#合并最大数 默认是 max_thread_count + 5个
# index.merge.scheduler.max_merge_count: 4

#是否自动限流 默认true
index.merge.scheduler.auto_throttle: true

#translog多久同步一次到磁盘，默认5s
index.translog.sync_interval: 5s

#是否可以选举为主节点，默认为true
#node.master: false

#所有breaker的父类设置，设置了这个值会覆盖所有的breaker其他设置，默认为JVM堆的70%
indices.breaker.total.limit: 70%

#字段数据缓存大小，默认为无界
indices.fielddata.cache.size: 20%

#字段断路器大小限制，默认JVM堆的60%
indices.breaker.fielddata.limit: 65%

#请求断路器大小限制，默认JVM堆的40%（限制在请求中计算聚合的内存超过设置大小）
indices.breaker.request.limit: 40%



#是否作为数据节点，默认为true
#node.data: false
# 本地开发模式，改为其他IP为生产模式
network.host: 0.0.0.0

#索引缓存引用类型，soft，当内存不足时jvm可回收掉
index.cache.field.type: soft
#锁定内存
bootstrap.memory_lock: true
#索引刷新时间，默认1s
index:refresh_interval: 8s

index.number_of_shards: 2
index.number_of_replicas: 0

#压缩存储方式 默认LZ4, 开启了 DEFLATE之后，索引确实小了点，索引时间变化不大，每次索引10w进行测试的。
#index.codec: best_compression

# result size. default = 10000
index.max_result_window: 10000

threadpool:
    index:
        size: 4
        queue_size: 1000

#indices.store.throttle.type: merge 
#写磁盘类型 
#indices.store.throttle.type: none 
indices.store.throttle.max_bytes_per_sec: 500mb

#index.search.slowlog.threshold.query.warn: 10s
#index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.query.debug: 1s
#index.search.slowlog.threshold.query.trace: 500ms
#
#index.search.slowlog.threshold.fetch.warn: 1s
#index.search.slowlog.threshold.fetch.info: 800ms
#index.search.slowlog.threshold.fetch.debug: 500ms
#index.search.slowlog.threshold.fetch.trace: 200ms
#
#index.indexing.slowlog.threshold.index.warn: 10s
#index.indexing.slowlog.threshold.index.info: 5s
#index.indexing.slowlog.threshold.index.debug: 2s
#index.indexing.slowlog.threshold.index.trace: 500ms


# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
# cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
# node.name: node-1
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
# path.data: /path/to/data
#
# Path to log files:
#
# path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.memory_lock: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
# http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]

discovery.zen.ping.unicast.hosts: ["127.0.0.1", "172.16.2.248", "172.16.4.33"]
#discovery.zen.ping.unicast.hosts: ["172.16.7.238"]
# 选举超时时间
discovery.zen.ping_timeout: 10s
discovery.zen.minimum_master_nodes: 1

#集群中没有master时 拒绝哪些操作 默认为写操作
discovery.zen.no_master_block: write

# How often a node gets pinged. Defaults to 1s.
# 故障检测间隔时间
discovery.zen.fd.ping_interval: 5s

# 默认时间为ping_timeout的20倍
#discovery.zen.join_timeout: 120s

#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
